### ISSUE TITLE
Box2D font

### ISSUE THREAD

**Issue by hondaman900** [atomic14/esp-asteroids#2]
Thank you for this project. Looks like it's missing the box2d.h file? Was wondering if this was an omission or intentional before I start commenting out references to that file....?

Here's the console build output:

```
In file included from src/Fonts/SimpleFont.hpp:5,
                 from src/Fonts/SimpleFont.cpp:1:
src/Fonts/Font.hpp:3:10: fatal error: box2d/box2d.h: No such file or directory
 #include "box2d/box2d.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by cgreening** [comment]
Sorry about that - forgot to add it a submodule. Can you try cloning again and use:

`git clone --recursive git@github.com:atomic14/esp-asteroids.git`

The `--recursive`  part will bring down the submodules.

**Comment by hondaman900** [comment]
No apologies necessary - many thanks for an awesome project.

Trying to `git clone` it from command line or from inside VS Code and I get the following error:

```
> git clone git@github.com:atomic14/esp-asteroids.git%20--recursive c:\Users\conco\Documents\ESP-32\Asteroids_2\esp-asteroids.git --recursive --progress
load pubkey "/c/Users/conco/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any ideas...?

**Comment by cgreening** [comment]
I think this might be that you don't have a valid SSH key setup with GitHub.

This bit seems to be broken: *load pubkey "/c/Users/conco/.ssh/id_rsa":
invalid format*

I've not seen that error before, but you could regenerate your keys and set
them up again with GitHub.

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

I think that will fix it.

You could also just switch to http for the cloning.

git clone --recursive https://github.com/atomic14/esp-asteroids.git

Cheers
Chris

**Comment by hondaman900** [comment]
Thanks Chris for the super-quick reply, I'll try the HTTP route. I git cloned the original project without issue. It seems the recursive inclusion of box2D is acting different.

Ok, tried that, looks like the security issue is with box2D:

```
git clone --recursive https://github.com/atomic14/esp-asteroids.git
Cloning into 'esp-asteroids'...
remote: Enumerating objects: 497, done.
remote: Counting objects: 100% (497/497), done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 497 (delta 296), reused 402 (delta 206), pack-reused 0 eceiving objects:  91% (453/497), 9.39 MiB | 1.09 MiB/s
Receiving objects: 100% (497/497), 9.74 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (296/296), done.
Submodule 'lib/box2d' (git@github.com:erincatto/box2d.git) registered for path 'lib/box2d'
Cloning into 'C:/Users/conco/Documents/ESP-32/Asteroids_2/esp-asteroids/lib/box2d'...
load pubkey "/c/Users/conco/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:erincatto/box2d.git' into submodule path 'C:/Users/conco/Documents/ESP-32/Asteroids_2/esp-asteroids/lib/box2d' failed
Failed to clone 'lib/box2d'. Retry scheduled
Cloning into 'C:/Users/conco/Documents/ESP-32/Asteroids_2/esp-asteroids/lib/box2d'...
load pubkey "/c/Users/conco/.ssh/id_rsa": invalid format
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:erincatto/box2d.git' into submodule path 'C:/Users/conco/Documents/ESP-32/Asteroids_2/esp-asteroids/lib/box2d' failed
Failed to clone 'lib/box2d' a second time, aborting
```

I could simply download the box2d repository zip files and extract into the lib subdirectory in your project. Would that work or does box2D have to be compiled first?

**Comment by cgreening** [comment]
Yes, so the submodule is still trying to use ssh.

Give it another go.

**Comment by hondaman900** [comment]
Yes! That worked - thank you. I'm awaiting a LM4040 for the voltage ref. The ADR5040 is unobtainable at the moment, probably due to the pandemic chip shortages. Not sure why a voltage ref is needed when the MCP4822 has one internally, but I'm trying to replicate your circuit as designed as my starting point. Don't want to change anything until after I have a working model :)  Many thanks for your help. What I'm hoping to achieve at the end is to send a data serial stream via BLE to your renderers to control the laser, rather than reading ILDA files, though the way you set that up with compressed files is genius. Thanks again :)

**Comment by cgreening** [comment]
Hey Stephen,

That sounds great!

The voltage reference is used for the output stage. The MCP4822 gives us a
single ended output from 0 - 4.096v

The Galvo needs a differential signal so we need to subtract 2.048V from
the signal and then send this new signal along with an inverted version to
get the differential pair.

signal+ = mcp4822 - 2.048
signal- = -(mcp4822 - 2.048)

Hope that makes sense.

Cheers
Chris

**Comment by hondaman900** [comment]
Yes indeed - many thanks Chris!
