### ISSUE TITLE
box2d missing

### ISSUE THREAD

**Issue by trevorboultwood** [atomic14/esp-asteroids#3]
Hi,

I wasnt sure if the other submitted issue was related to this but the box2d lib doesn't seem to exist. Thank you, I still owe you some pictures and videos of my RGB laser display and hope to add colour to your project!

**Comment by cgreening** [comment]
Make sure you do the `--recursive` when you clone.

```
git clone --recursive git@github.com:atomic14/esp-asteroids.git
```

That should pull down the box2d lib. Let me know if it's still not working.

Definitely share the videos and pictures! We've got a discord channel now and I'm sure people would like to see them: https://discord.gg/JEKhw4TaW8

**Comment by trevorboultwood** [comment]
I need to get upto date with git, I just 'downloaded .zip' like i always do. I downloaded the gitDesktop application and it downloaded/cloned all the required libraries and managed to build your project successfully so thank you very much. I joined your discord and typed a burb of my project, happy to elaborate if youre interested

Thank you!
