### ISSUE TITLE
rotate world screen

### ISSUE THREAD

**Issue by jschoch** [atomic14/esp-asteroids#4]
my output is rotated 90 degrees, is there an easy way to rotate the world box?

PS thanks for sharing this.  I had a bunch of issues with your ilda file renderer in your other library but this is working at rendering fonts.  I don't have an encoder hooked up yet.

PPS First thought is active noise canceling for the galvo, wonder how hard that would be.

**Comment by cgreening** [comment]
Thanks! I'm sorry you had issues with the ILDA project - I'll take a look at the issues on it.

The simplest way is to swap the X and Y galvo inputs and if things are the wrong way round reverse the polarity on whichever is upside down or back to front. May take a bit of experimenting to get it right.

**Comment by jschoch** [comment]
yup, i had my wires wrong, figured it out!  Text is rendering ok.  Trying to get an animated clock running, seems my aspect ratio is a bit stretched out, not sure if that is  the galvo or my setup.
