### ISSUE TITLE
won't build with current platformio in current vscode

### ISSUE THREAD

**Issue by a2ff** [atomic14/esp-asteroids#5]
platformio.ini does not use a version specifier for platform=espressif32 so it uses the latest which today is 6.3.2
the build warnings and errors are typical of what one gets when source code is out-of-date vs. changes in some dependencies.
=> could you tell us which version of espressif32 you last successfully built with?

**Comment by cgreening** [comment]
Fixed by https://github.com/atomic14/esp-asteroids/pull/7
